export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const INCREASE_ITEM = 'INCREASE_ITEM';
export const DECREASE_ITEM = 'DECREASE_ITEM';
export const DISPLAY_LOADER = 'DISPLAY_LOADER';
export const FETCH_ITEMS = 'DECREASE_ITEM';
